/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hrm.ui;

import com.hrm.controlller.Main;
import com.hrm.dao.NhanVienDAO;
import com.hrm.dao.impl.NhanVienDAOImpl;
import com.hrm.entity.NhanVien;
import com.hrm.util.Auth;
import com.hrm.util.XImage;
import com.hrm.util.MsgBox;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus k550j
 */
public class HRM extends javax.swing.JFrame implements Main {

    /**
     * Creates new form Poly
     */
    public HRM() {
        initComponents();
        this.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTrump = new javax.swing.JPanel();
        pnlttcn = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPB = new javax.swing.JLabel();
        lblTrump = new javax.swing.JLabel();
        toolBar = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnNhanVien = new javax.swing.JButton();
        btnChamCong = new javax.swing.JButton();
        btnBangLuong = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        TbtnDarkMode = new javax.swing.JToggleButton();
        btnTTCN = new javax.swing.JToggleButton();
        pnlStatusBar = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniKhoaHoc = new javax.swing.JMenuItem();
        mniNguoiHoc = new javax.swing.JMenuItem();
        mniHocVien = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniTKNV = new javax.swing.JMenuItem();
        TKLTT = new javax.swing.JMenuItem();
        TKTLC = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ NHÂN SỰ");

        pnlTrump.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlttcn.setBackground(new java.awt.Color(0, 204, 153));
        pnlttcn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Book.png"))); // NOI18N
        lblHinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        lblHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });
        pnlttcn.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 130));

        jLabel1.setText("Họ và tên :");
        pnlttcn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, -1));

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoTen.setText("jLabel2");
        pnlttcn.add(lblHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, -1));

        jLabel3.setText("Chức vụ :");
        pnlttcn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, -1));

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChucVu.setText("jLabel2");
        pnlttcn.add(lblChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, -1));

        jLabel5.setText("Phòng ban :");
        pnlttcn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, -1));

        lblPB.setBackground(new java.awt.Color(204, 204, 204));
        lblPB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPB.setText("jLabel2");
        pnlttcn.add(lblPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, -1));

        pnlTrump.add(pnlttcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 180, 480));

        lblTrump.setBackground(new java.awt.Color(89, 168, 120));
        lblTrump.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblTrump.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrump.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/hrm.png"))); // NOI18N
        lblTrump.setText("QUẢN LÝ NHÂN SỰ");
        lblTrump.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTrump.setOpaque(true);
        lblTrump.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlTrump.add(lblTrump, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 500));

        getContentPane().add(pnlTrump, java.awt.BorderLayout.CENTER);

        toolBar.setBackground(new java.awt.Color(0, 49, 64));
        toolBar.setFloatable(false);
        toolBar.setForeground(new java.awt.Color(255, 255, 255));

        btnDangXuat.setBackground(new java.awt.Color(0, 49, 64));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/logout.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnDangXuat.setRolloverEnabled(false);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        toolBar.add(btnDangXuat);

        btnKetThuc.setBackground(new java.awt.Color(0, 49, 64));
        btnKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKetThuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/exit_1.png"))); // NOI18N
        btnKetThuc.setText("Kết thúc");
        btnKetThuc.setFocusable(false);
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnKetThuc.setRolloverEnabled(false);
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        toolBar.add(btnKetThuc);
        toolBar.add(jSeparator6);

        btnNhanVien.setBackground(new java.awt.Color(0, 49, 64));
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/chuyende.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnNhanVien.setRolloverEnabled(false);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        toolBar.add(btnNhanVien);

        btnChamCong.setBackground(new java.awt.Color(0, 49, 64));
        btnChamCong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChamCong.setForeground(new java.awt.Color(255, 255, 255));
        btnChamCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/student.png"))); // NOI18N
        btnChamCong.setText("Chấm công");
        btnChamCong.setFocusable(false);
        btnChamCong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChamCong.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnChamCong.setRolloverEnabled(false);
        btnChamCong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCongActionPerformed(evt);
            }
        });
        toolBar.add(btnChamCong);

        btnBangLuong.setBackground(new java.awt.Color(0, 49, 64));
        btnBangLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBangLuong.setForeground(new java.awt.Color(255, 255, 255));
        btnBangLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/khoahoc.png"))); // NOI18N
        btnBangLuong.setText("Bảng lương");
        btnBangLuong.setFocusable(false);
        btnBangLuong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBangLuong.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnBangLuong.setRolloverEnabled(false);
        btnBangLuong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBangLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangLuongActionPerformed(evt);
            }
        });
        toolBar.add(btnBangLuong);

        btnHocVien.setBackground(new java.awt.Color(0, 49, 64));
        btnHocVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHocVien.setForeground(new java.awt.Color(255, 255, 255));
        btnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/staff.png"))); // NOI18N
        btnHocVien.setText("Thưởng/Kỷ luật");
        btnHocVien.setFocusable(false);
        btnHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocVien.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnHocVien.setRolloverEnabled(false);
        btnHocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        toolBar.add(btnHocVien);
        toolBar.add(jSeparator7);

        btnHuongDan.setBackground(new java.awt.Color(0, 49, 64));
        btnHuongDan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuongDan.setForeground(new java.awt.Color(255, 255, 255));
        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/earth.png"))); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnHuongDan.setRolloverEnabled(false);
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        toolBar.add(btnHuongDan);

        TbtnDarkMode.setBackground(new java.awt.Color(0, 49, 64));
        TbtnDarkMode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TbtnDarkMode.setForeground(new java.awt.Color(255, 255, 255));
        TbtnDarkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/moon.png"))); // NOI18N
        TbtnDarkMode.setText("Dark mode");
        TbtnDarkMode.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TbtnDarkMode.setFocusable(false);
        TbtnDarkMode.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        TbtnDarkMode.setRolloverEnabled(false);
        TbtnDarkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnDarkModeActionPerformed(evt);
            }
        });
        toolBar.add(TbtnDarkMode);

        btnTTCN.setBackground(new java.awt.Color(0, 49, 64));
        btnTTCN.setForeground(new java.awt.Color(255, 255, 255));
        btnTTCN.setText("Thông tin cá nhân");
        btnTTCN.setFocusable(false);
        btnTTCN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTTCN.setRolloverEnabled(false);
        btnTTCN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTTCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTCNActionPerformed(evt);
            }
        });
        toolBar.add(btnTTCN);

        getContentPane().add(toolBar, java.awt.BorderLayout.NORTH);

        pnlStatusBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnlStatusBar.setLayout(new java.awt.BorderLayout());

        lblTrangThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Info.png"))); // NOI18N
        lblTrangThai.setText("Hệ quản lý đào tạo");
        lblTrangThai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        pnlStatusBar.add(lblTrangThai, java.awt.BorderLayout.CENTER);

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Alarm.png"))); // NOI18N
        lblDongHo.setText("10:55 PM");
        lblDongHo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pnlStatusBar.add(lblDongHo, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlStatusBar, java.awt.BorderLayout.SOUTH);

        mnuHeThong.setText("Hệ thống");

        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/changePass.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator2);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/logout.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator1);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/exit_1.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        menuBar.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");

        mniKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/khoahoc.png"))); // NOI18N
        mniKhoaHoc.setText("Bảng Lương");
        mniKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoaHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKhoaHoc);

        mniNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/student.png"))); // NOI18N
        mniNguoiHoc.setText("Chấm Công");
        mniNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoiHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNguoiHoc);

        mniHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/staff.png"))); // NOI18N
        mniHocVien.setText("Thưởng/Kỷ Luật");
        mniHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHocVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniHocVien);
        mnuQuanLy.add(jSeparator4);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/User group.png"))); // NOI18N
        mniNhanVien.setText("Nhân Viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        menuBar.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");
        mnuThongKe.add(jSeparator3);

        mniTKNV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniTKNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Clien list.png"))); // NOI18N
        mniTKNV.setText("Thống kê nhân viên");
        mniTKNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTKNVActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniTKNV);

        TKLTT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        TKLTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Bar chart.png"))); // NOI18N
        TKLTT.setText("Thống kê lương theo tháng");
        TKLTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKLTTActionPerformed(evt);
            }
        });
        mnuThongKe.add(TKLTT);

        TKTLC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        TKTLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Dollar.png"))); // NOI18N
        TKTLC.setText("Tổng lương chi");
        TKTLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKTLCActionPerformed(evt);
            }
        });
        mnuThongKe.add(TKTLC);

        menuBar.add(mnuThongKe);

        mnuTroGiup.setText("Trợ giúp");

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Globe.png"))); // NOI18N
        mniHuongDan.setText("Hướng dẫn sử dụng");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHuongDan);
        mnuTroGiup.add(jSeparator5);

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Brick house.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu sản phẩm");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu);

        menuBar.add(mnuTroGiup);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCongActionPerformed
        // TODO add your handling code here:
        this.openChamCong();
    }//GEN-LAST:event_btnChamCongActionPerformed

    private void btnBangLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangLuongActionPerformed
        // TODO add your handling code here:
        this.openLuong();
    }//GEN-LAST:event_btnBangLuongActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoiHocActionPerformed
        // TODO add your handling code here:
        this.openChamCong();
    }//GEN-LAST:event_mniNguoiHocActionPerformed

    private void mniKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoaHocActionPerformed
        // TODO add your handling code here:
        this.openLuong();
    }//GEN-LAST:event_mniKhoaHocActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void mniTKNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTKNVActionPerformed
        // TODO add your handling code here:
        this.openThongKe(0);
    }//GEN-LAST:event_mniTKNVActionPerformed

    private void TKLTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKLTTActionPerformed
        // TODO add your handling code here:
        this.openThongKe(1);
    }//GEN-LAST:event_TKLTTActionPerformed

    private void TKTLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKTLCActionPerformed
        // TODO add your handling code here:
        this.openThongKe(2);
    }//GEN-LAST:event_TKTLCActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        // TODO add your handling code here:
        this.openGioiThieu();
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_mniHuongDanActionPerformed

    private void mniHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHocVienActionPerformed
        // TODO add your handling code here:
        this.openThuongVaKyLuat();
    }//GEN-LAST:event_mniHocVienActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        // TODO add your handling code here:
        this.openThuongVaKyLuat();
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void TbtnDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnDarkModeActionPerformed
        if (TbtnDarkMode.isSelected()) {
            this.darkMode(1);
        } else {
            this.darkMode(0);
        }
    }//GEN-LAST:event_TbtnDarkModeActionPerformed
    NhanVienDAO dao = new NhanVienDAOImpl();
    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_lblHinhMouseClicked

    private void btnTTCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTCNActionPerformed
        // TODO add your handling code here:
        if (btnTTCN.isSelected()) {
            pnlttcn.show(true);
        } else {
            pnlttcn.show(false);

        }
    }//GEN-LAST:event_btnTTCNActionPerformed
    public void chonAnh(NhanVien nv) {

        ImageIcon icon = XImage.read(nv.getHinh(), lblHinh); // đọc hình từ logos
        lblHinh.setIcon(icon);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem TKLTT;
    private javax.swing.JMenuItem TKTLC;
    private javax.swing.JToggleButton TbtnDarkMode;
    private javax.swing.JButton btnBangLuong;
    private javax.swing.JButton btnChamCong;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JToggleButton btnTTCN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblPB;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrump;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHocVien;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniKhoaHoc;
    private javax.swing.JMenuItem mniNguoiHoc;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniTKNV;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlStatusBar;
    private javax.swing.JPanel pnlTrump;
    private javax.swing.JPanel pnlttcn;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
    @Override
    public void initialize() {
        pnlttcn.show(false);
        setIconImage(XImage.getAppIcon());
        setSize(1000, 600);
        setLocationRelativeTo(null);
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);
        lblTrangThai.setText("Mã nhân viên: " + Auth.user.getMaNV() + " | " + "Chức vụ: " + Auth.isManager());
        this.time();
        NhanVien nv = dao.getById(Auth.user.getMaNV());
        this.chonAnh(nv);
        lblHoTen.setText(nv.getHoTen());
        lblChucVu.setText(nv.getMaCV() == 1 ? "Trưởng Phòng" : "Nhân viên");
        lblPB.setText(nv.getMaCV() == 1 ? "Phòng kế toán" : "Phòng bán hàng");

//        if (!Auth.isManager()) {
//            mniNhanVien.setEnabled(false);
//            mniDoanhThu.setEnabled(false);
//        } else {
//            mniNhanVien.setEnabled(true);
//            mniDoanhThu.setEnabled(true);
//
//        }
    }

    @Override
    public void time() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    SimpleDateFormat df = new SimpleDateFormat();
                    //Lấy thời gian
                    df.applyPattern("hh:mm:ss a");
                    //Lấy thời gian thực
                    Date d = new Date();
                    //chuyển đổi thời gian hiện tại sang dạng Chuỗi ký tự
                    String sThoiGian = df.format(d);
                    lblDongHo.setText(sThoiGian);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        }.start();

    }

    @Override
    public void darkMode(int status) {
        if (status == 1) {
            lblTrump.setBackground(Color.darkGray);
            toolBar.setBackground(Color.gray);
        } else {
            Color toolbarcolor = new Color(0, 49, 64);
            Color centercolor = new Color(89, 168, 120);
            lblTrump.setBackground(centercolor);
            toolBar.setBackground(toolbarcolor);
        }

    }

    @Override
    public void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    @Override
    public void dangXuat() {
        Auth.clear();
        new DangNhapJDialog(this, true).setVisible(true);
        lblTrangThai.setText("Mã nhân viên: " + Auth.user.getMaNV() + " | " + "Chức vụ: " + Auth.isManager());
//        if (!Auth.isManager()) {
//            mniNhanVien.setEnabled(false);
//            mniDoanhThu.setEnabled(false);
//
//        } else {
//            mniNhanVien.setEnabled(true);
//            mniDoanhThu.setEnabled(true);
//
//        }
    }

    @Override
    public void ketThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc?")) {
            System.exit(0);
        }
    }

    @Override
    public void openNhanVien() {
        if (Auth.isLogin()) {
            if (Auth.isManager().equalsIgnoreCase("Trưởng phòng kế toán") || Auth.isManager().equalsIgnoreCase("Nhân viên")) {
                MsgBox.alert(this, "Bạn không có quyền xem thông tin nhân viên!!!");
                return;
            }
            new NhanVienJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    @Override
    public void openLuong() {
        if (Auth.isLogin()) {
            if (Auth.isManager().equalsIgnoreCase("Trưởng phòng bán hàng") || Auth.isManager().equalsIgnoreCase("Nhân viên")) {
                MsgBox.alert(this, "Bạn không có quyền xem thông tin lương!!!");
                return;
            }
            new LuongJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    @Override
    public void openChamCong() {
        if (Auth.isLogin()) {
            if (Auth.isManager().equalsIgnoreCase("Trưởng phòng kế toán") || Auth.isManager().equalsIgnoreCase("Nhân viên")) {
                MsgBox.alert(this, "Bạn không có quyền chấm công!!!");
                return;
            }
            new ChamCongJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    @Override
    public void openThuongVaKyLuat() {
        if (Auth.isLogin()) {
            if (Auth.isManager().equalsIgnoreCase("Trưởng phòng kế toán") || Auth.isManager().equalsIgnoreCase("Nhân viên")) {
                MsgBox.alert(this, "Bạn không có quyền thưởng hoặc kỉ luật!!!");
                return;
            }
            new ThuongVaKyLuatJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    @Override
    public void openThongKe(int index) {
        if (Auth.isLogin()) {
            if (Auth.isManager().equalsIgnoreCase("Trưởng phòng bán hàng") || Auth.isManager().equalsIgnoreCase("Nhân viên")) {
                MsgBox.alert(this, "Bạn không có quyền xem thông tin Thống kê");
                return;
            }
            ThongKeJDialog tkwin = new ThongKeJDialog(this, true);
            tkwin.selectTab(index);

            tkwin.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    @Override
    public void openGioiThieu() {
        new GioiThieuJDialog(this, true).setVisible(true);
    }

    @Override
    public void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (IOException ex) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }

}
