/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hrm.ui;

import com.hrm.controlller.QuenMatKhauController;
import com.hrm.dao.NhanVienDAO;
import com.hrm.dao.impl.NhanVienDAOImpl;
import com.hrm.entity.NhanVien;
import com.hrm.util.Auth;
import com.hrm.util.Mail;
import com.hrm.util.MsgBox;
import com.hrm.util.XImage;
import java.util.List;

/**
 *
 * @author ADMIN
 */
public class QuenMatKhauJDialog extends javax.swing.JDialog implements QuenMatKhauController {

    /**
     * Creates new form QuenMatKhauJDialog
     */
    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtMaXacMinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TbtnGuiMa = new javax.swing.JToggleButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Email.gif"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtMaXacMinh.setBorder(javax.swing.BorderFactory.createTitledBorder("Mã xác nhận:"));
        txtMaXacMinh.setEnabled(false);
        txtMaXacMinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaXacMinhActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Email.gif"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/Tick.png"))); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnXacNhan.setBorderPainted(false);
        btnXacNhan.setEnabled(false);
        btnXacNhan.setFocusPainted(false);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/icon/No.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnHuy.setBorderPainted(false);
        btnHuy.setFocusPainted(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("EMAIL");

        TbtnGuiMa.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        TbtnGuiMa.setForeground(new java.awt.Color(0, 0, 255));
        TbtnGuiMa.setText("Gửi mã");
        TbtnGuiMa.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TbtnGuiMa.setBorderPainted(false);
        TbtnGuiMa.setFocusPainted(false);
        TbtnGuiMa.setFocusable(false);
        TbtnGuiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnGuiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaXacMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(58, 58, 58))
                            .addComponent(TbtnGuiMa))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TbtnGuiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaXacMinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaXacMinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaXacMinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaXacMinhActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        this.xacNhan();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void TbtnGuiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnGuiMaActionPerformed
        this.guiMa();
    }//GEN-LAST:event_TbtnGuiMaActionPerformed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        txtEmail.setEditable(true);
        txtEmail.requestFocus();
        txtEmail.setEnabled(true);
        btnXacNhan.setEnabled(false);
        txtMaXacMinh.setText("");
        txtMaXacMinh.setEnabled(false);


    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased

    }//GEN-LAST:event_txtEmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton TbtnGuiMa;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaXacMinh;
    // End of variables declaration//GEN-END:variables

    NhanVienDAO nvdao = new NhanVienDAOImpl();
    List<NhanVien> list;

    @Override
    public void guiMa() {
        if (txtEmail.getText().equals("")) {
            MsgBox.alert(this, "Email không được để trống !");
            TbtnGuiMa.setSelected(false);
            return;
        }
        if (TbtnGuiMa.isSelected()) {
            sendMail();
            TbtnGuiMa.setSelected(false);
            this.time(15);

        }
    }

    @Override
    public boolean xacNhan() {
        try {
            if (txtMaXacMinh.isEnabled()) {
                if (txtMaXacMinh.getText().equals("")) {
                    MsgBox.alert(this, "Mã xác nhận không được để trống !");
                    TbtnGuiMa.setSelected(false);
                    return false;
                } else if (!txtMaXacMinh.getText().equals("190420")) {
                    MsgBox.alert(this, "Mã xác nhận không trùng khớp !");
                    TbtnGuiMa.setSelected(false);
                    return false;

                }
            }
            Auth.user = list.get(0);

            new DoiMatKhauJDialog(null, true).setVisible(true);
            this.dispose();
            return true;
        } catch (Exception e) {
            return false;
        }

    }

    @Override
    public void initialize() {
        setLocationRelativeTo(null);
        setIconImage(XImage.getAppIcon());
        this.setTitle("HRM - Email");
        this.time(-1);
    }

    @Override
    public void time(int value) {
        new Thread() {
            int i = value;

            @Override
            public void run() {
                while (i >= 0) {
                    TbtnGuiMa.setEnabled(false);
                    TbtnGuiMa.setText("Gửi mã(" + i + ")");
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                    i--;
                    TbtnGuiMa.setEnabled(true);
                    TbtnGuiMa.setText("Gửi mã");
                }

            }
        }.start();
    }

    @Override
    public void sendMail() {
        new Thread() {
            @Override
            public void run() {
                while (txtEmail.isEditable()) {
                    String email = txtEmail.getText().trim();
                    list = nvdao.searchByEmail(email);
                    if (!list.isEmpty()) {
                        new Mail(email);
                        txtEmail.setEditable(false);
                        txtMaXacMinh.setEnabled(true);
                        btnXacNhan.setEnabled(true);

                    } else {
                        MsgBox.alert(null, "Email của bạn không tồn tại trong hệ thống HRM !");
                        txtMaXacMinh.setEnabled(false);
                        break;
                    }

                }
            }
        }.start();

    }

}
