/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hrm.ui;

import com.hrm.controlller.ThongKeController;
import com.hrm.dao.impl.ThongKeDAOImpl;
import com.hrm.entity.ThongKe;
import com.hrm.util.XPrint;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ThongKeJDialog extends javax.swing.JDialog implements ThongKeController {

    /**
     * Creates new form ThongKeJDialog
     */
    public ThongKeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLuongTheoThang = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtThoiGian = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLuongAll = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HRM - Tổng hợp và thống kê");

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PHÒNG BAN", "TỔNG NHÂN VIÊN", "NAM", "NỮ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setRowHeight(25);
        jScrollPane1.setViewportView(tblNhanVien);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabs.addTab("NHÂN VIÊN", jPanel1);

        jPanel3.setLayout(new java.awt.BorderLayout());

        tblLuongTheoThang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "THÁNG", "PHÒNG BAN", "SỐ TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLuongTheoThang.setRowHeight(25);
        jScrollPane2.setViewportView(tblLuongTheoThang);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("THỜI GIAN:");
        jPanel7.add(jLabel3, java.awt.BorderLayout.LINE_START);

        txtThoiGian.setDateFormatString("y");
        txtThoiGian.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtThoiGianPropertyChange(evt);
            }
        });
        jPanel7.add(txtThoiGian, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        tabs.addTab("LƯƠNG CHI THEO THÁNG", jPanel3);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblLuongAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PHÒNG BAN", "TỔNG TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLuongAll.setRowHeight(25);
        jScrollPane3.setViewportView(tblLuongAll);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabs.addTab("TỔNG LƯƠNG CHI", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("TỔNG HỢP THỐNG KÊ");

        btnPrint.setText("In danh sách");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrint)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtThoiGianPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtThoiGianPropertyChange
        if (evt.getPropertyName().equals("date")) {
            this.fillTableLuongThang();

        }
    }//GEN-LAST:event_txtThoiGianPropertyChange

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        this.Print();
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongKeJDialog dialog = new ThongKeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblLuongAll;
    private javax.swing.JTable tblLuongTheoThang;
    private javax.swing.JTable tblNhanVien;
    private com.toedter.calendar.JDateChooser txtThoiGian;
    // End of variables declaration//GEN-END:variables

    ThongKeDAOImpl tkdao = new ThongKeDAOImpl();
    List<ThongKe.thongKeNV> list;
    List<ThongKe.thongKeLuongThang> listLT;
    DecimalFormat df = new DecimalFormat("#,### VND");

    public void selectTab(int index) {
        tabs.setSelectedIndex(index);
    }

    @Override
    public void initialize() {
        this.setLocationRelativeTo(null);
        this.fillTableNV();
        this.fillTableLuongThang();
        this.fillTableLuongAll();

    }

    @Override
    public void fillTableNV() {
        list = tkdao.getListNV();
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);

        for (ThongKe.thongKeNV e : list) {
            Object[] row = {e.getMaPB() == 1 ? "Phòng kế toán" : "Phòng bán hàng", e.getTongNV(), e.getSlNam(), e.getSlNu()};
            model.addRow(row);

        }
    }

    @Override
    public void fillTableLuongThang() {
        try {
            listLT = tkdao.getListLuongThang(txtThoiGian.getDate().getYear() + 1900);
            DefaultTableModel model = (DefaultTableModel) tblLuongTheoThang.getModel();
            model.setRowCount(0);
            for (ThongKe.thongKeLuongThang e : listLT) {
                Object[] row = {"Tháng " + e.getThoiGian().getMonth(), e.getTenPB(), df.format(e.getSoTien())};
                model.addRow(row);

            }
        } catch (Exception e) {
        }

    }

    @Override
    public void fillTableLuongAll() {
        try {
            listLT = tkdao.getListLuongAll(0);
            DefaultTableModel model = (DefaultTableModel) tblLuongAll.getModel();
            model.setRowCount(0);
            for (ThongKe.thongKeLuongThang e : listLT) {
                Object[] row = {e.getTenPB(), df.format(e.getSoTien())};
                model.addRow(row);

            }
        } catch (Exception e) {
        }
    }

    @Override
    public void Print() {
        if (tabs.getSelectedIndex() == 0) {
            XPrint.Print((DefaultTableModel) tblNhanVien.getModel());
        } else if (tabs.getSelectedIndex() == 1) {
            XPrint.Print((DefaultTableModel) tblLuongTheoThang.getModel());
        } else {
            XPrint.Print((DefaultTableModel) tblLuongAll.getModel());
        }
    }

}
